version: '3.9'
services:
  ec-nemisys:
    image: 'docker.easecation.net/nemisys'
    container_name: 'ec-nemisys'
    build: '.'
    ports:
      - '19132:19132/udp'
      - '10305:10305/tcp'
    stdin_open: true
